### ISSUE TITLE
Possible to specify env per project within Atom dir

### ISSUE THREAD

**Issue by jerone** [kohkimakimoto/atom-atomenv#2]
It would be great to push environment variables per project, using an env file within the Atom dir. E.g.:

```
{
    "atom-atomenv" : {
        "env": {
            "FOO": "bar"
        }
    },
    "my-project": {
        "env": {
            "FOO": "bar"
        }
    }
}
```

To set variables for all projects, you can use the `*` like Atom does for the config file, e.g.:

```
{
    "*": {
        "env": {
            "FOO": "bar"
        }
    },
    "atom-atomenv" : {
        "env": {
            "FOO": "bar"
        }
    }
}
```

**Comment by kohkimakimoto** [comment]
Is **Atom dir** the `$ATOM_HOME`? 
For example `~/.atom`?

**Comment by jerone** [comment]
Yes.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
