### ISSUE TITLE
atomenv with go-plus?

### ISSUE THREAD

**Issue by scippio** [kohkimakimoto/atom-atomenv#4]
Is possible use atomenv and GOPATH definition with go-plus package? I setup .atomenv.json in my project directory, but when I open new project the go-plus pkg still have old (default) GOPATH value... :thinking:

**Comment by kohkimakimoto** [comment]
Sorry, I don't know. I have not used go-plus package and I have not used this package now,
Now, I am using vscode instead of atom. So atomenv is not maintained no longer.

**Comment by scippio** [comment]
ok, thanks for response...
